version: 2.1

jobs:
  pypi_publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload -u __token__ -p $PYPI_TOKEN dist/*

workflows:
  publish:
    jobs:
      - pypi_publish:
          filters:
            branches:
              only:
                - main